name: Image Build and Trigger K3s

on:
  workflow_call:
    secrets:
      REGISTRY_URL:
        required: true
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true
      PERSONAL_ACCESS_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/arti-${{ github.event.repository.name }}:${{ github.event.release.tag_name }}
  
  trigger:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger K3s Repo
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: 'k3s',
              workflow_id: 'update-and-add-tag.yml',
              ref: 'main',
              inputs: {
                project_version: '${{ github.event.release.tag_name }}',
                project_name: '${{ github.event.repository.name }}',
              },
            })
