name: Django Test

on:
  workflow_call:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres: 
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ciuser
          POSTGRES_PASSWORD: cipassword
          POSTGRES_DB: cidb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
      POETRY_VIRTUALENVS_IN_PROJECT: true
      POETRY_NO_INTERACTION: 1
      POETRY_HOME: "/opt/poetry"
      POETRY_VERSION: 1.7.1

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry=="$POETRY_VERSION"

      - name: Install Dependencies with Poetry
        run: |
          poetry install --no-dev --no-root

      - name: Set up vars variables
        run: |
          cp .env.ci .env

      - name: Run Migrations
        run: |
          poetry run python manage.py migrate

      - name: Run Unit Tests
        run: |
          poetry run python manage.py test

      - name: Run Behave Tests
        run: |
          poetry run python manage.py behave --no-input
